sonar.projectKey=AMINEM-1337_task-cicd-app
sonar.organization=AMINEM-1337

sonar.sources=.
sonar.tests=tests

sonar.test.inclusions=tests/**/*.py
sonar.exclusions=venv/**,.venv/**,__pycache__/**,.pytest_cache/**,tasks.db

sonar.python.version=3.12
